baseURL = 'https://bulesky29.com/'
languageCode = 'en-us'
title = 'Bulesky29のblog'
theme = ["github.com/D-Sketon/hugo-theme-reimu"]

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[security.headers]
  [security.headers.contentSecurityPolicy]
    frameAncestors = ["'self'", "https://giscus.app/"]