name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - hugo

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install obsidian-export
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/zoni/obsidian-export/releases/download/v25.3.0/obsidian-export-installer.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Prepare Hugo content directories
        run: |
          # 清理旧的 content 目录，确保每次构建都是干净的
          rm -rf tianyi_site/content/posts
          rm -rf tianyi_site/content/archives
          rm -rf tianyi_site/content/about.md
          rm -rf tianyi_site/content/friend.md
          mkdir -p tianyi_site/content/posts
          mkdir -p tianyi_site/content/archives

      - name: Export Obsidian vault to Hugo content
        run: |
          # 运行导出命令，直接导出到 tianyi_site/content/posts
          obsidian-export \
            vaults/blog \
            tianyi_site/content/posts

      - name: Move special pages and archives
        run: |
          # 移动 archives 到独立目录
          if [ -d "tianyi_site/content/posts/archives" ]; then
            mv tianyi_site/content/posts/archives/* tianyi_site/content/archives/
            rm -r tianyi_site/content/posts/archives
          fi
          # 移动 about.md 和 friend.md 到 content 根目录
          if [ -f "tianyi_site/content/posts/about.md" ]; then
            mv tianyi_site/content/posts/about.md tianyi_site/content/
          fi
          if [ -f "tianyi_site/content/posts/friend.md" ]; then
            mv tianyi_site/content/posts/friend.md tianyi_site/content/
          fi
          rm -r tianyi_site/content/posts/00-template

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Run Hugo mod tidy and build site
        run: |
          hugo mod tidy --source tianyi_site
          hugo --source tianyi_site --destination public

      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./tianyi_site/public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4