name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - hugo

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install obsidian-export
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/zoni/obsidian-export/releases/download/v25.3.0/obsidian-export-installer.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Prepare Content from Obsidian Vault
        run: |
          echo "--- 1. Cleaning and creating directories ---"
          # 清理并重建临时目录和内容目录，确保构建环境干净
          rm -rf tianyi_site/content/post
          rm -rf tianyi_site/content/archives
          rm -rf tmp
          mkdir -p tianyi_site/content/post
          mkdir -p tianyi_site/content/archives
          mkdir -p tmp
          
          echo "--- 2. Tidying Hugo modules ---"
          # 根据 go.mod 清理 Hugo 模块
          hugo mod tidy --source tianyi_site
          
          echo "--- 3. Exporting from Obsidian vault ---"
          # 将 Obsidian vault 内容复制到临时目录进行处理
          cp -r vaults/blog tmp
          # 移除不需要的模板文件
          rm -r tmp/blog/00-template
          rm -r tmp/blog/.obsidian
          # 执行导出
          obsidian-export tmp/blog tianyi_site/content/post
          
          echo "--- 4. Organizing content ---"
          # 移动 'archives' 目录下的文章
          if [ -d "tianyi_site/content/post/archives" ]; then
            mv tianyi_site/content/post/archives/* tianyi_site/content/archives/
            rm -r tianyi_site/content/post/archives
          fi
          # 移动 'about.md' 页面
          if [ -f "tianyi_site/content/post/about.md" ]; then
            mv tianyi_site/content/post/about.md tianyi_site/content/
          fi
          # 移动 'friend.md' 页面
          if [ -f "tianyi_site/content/post/friend.md" ]; then
            mv tianyi_site/content/post/friend.md tianyi_site/content/
          fi
          
          echo "--- Content preparation complete ---"


      - name: Build Hugo Site
        run: |
          hugo --source tianyi_site --destination public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./tianyi_site/public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4